version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  fastapi:
    build: ./main_app
    volumes:
      - ./main_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    restart: always

  worker1:
    build: ./worker1
    volumes:
      - ./worker1:/app
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    restart: always

  worker2:
    build: ./worker2
    volumes:
      - ./worker2:/app
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    restart: always

  flower:
    image: "mher/flower"
    volumes:
      - ./main_app:/data
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - rabbitmq
      - worker1
    restart: always
    command: ["celery", "flower", "--broker=amqp://guest:guest@rabbitmq:5672/", "--port=5555", "--logging=DEBUG", "--address=0.0.0.0"]
